### ISSUE TITLE
Serde: Could not convert Hcl into Rust types

### ISSUE THREAD

**Issue by in0rdr** [pipelight/pipelight#14]
Thank you for creating this awesome project. I saw that it supports writing a pipeline in HCL syntax which I find fantastic.

I quickly tried it out this evening, but could not figure it out right away, because the example pipeline did not compile on my machine:

```bash
$ pipelight run
Error: cast::hcl

  × Serde: Could not convert Hcl into Rust types
  ╰─▶ invalid type: map, expected a sequence
   ╭─[1:1]
 1 │ pipelines {
   · ▲
   · ╰── here
 2 │   name = "simple_example2"
 3 │   steps {
 4 │     name     = "list directory"
   ╰────
```

What do I miss? Thanks

**Comment by pipelight** [comment]
I don't know if it is inherent to hcl but the block syntax isn't accepted when there is a single pipeline definition

This works


```rs
# A pipeline
pipelines {
  name = "simple_example"
  steps {
    name     = "list directory"
    commands = ["ls"]
  }
  steps {
    name     = "get working directory"
    commands = ["pwd"]
  }
}

# Another pipeline
pipelines {
  name = "simple_example2"
  steps {
    name     = "list directory"
    commands = ["ls"]
  }
  steps {
    name     = "get working directory"
    commands = ["pwd"]
  }
}

```
This doesn't

```rs
# A pipeline
pipelines {
  name = "simple_example"
  steps {
    name     = "list directory"
    commands = ["ls"]
  }
  steps {
    name     = "get working directory"
    commands = ["pwd"]
  }
}
```

I just changed the template to use the array syntax

```rs
pipelines = [{
  name = "simple_example"
  steps = [{
      name     = "list directory"
      commands = ["ls"]
    },
    {
      name     = "get working directory"
      commands = ["pwd"]
  }]
}]
```

This hotfix only circumvent the problem. I will dig further in the crate and in hcl specification to see what happened.

**Comment by pipelight** [comment]
Thank you very much and thank you for bearing opening this issue.

**Comment by pipelight** [comment]
So this is due to rust implementation of hcl deserialization.
When a block is not repeted, it is stored as an Object but Pipelight needs a Vector of Objects.
For now, there is not much I can do about it. I have tried a few things but nothing convincing.

**Comment by in0rdr** [comment]
Indeed I tried it with just one pipeline and that's the reason it failed. When using it with the list syntax you suggested it works. Thanks for clarification, that bug was clearly on my side :smile: Feel free to close the issue.
