### ISSUE TITLE
Package 'pipelight' installation fails on aarch64-darwin platform via Nix

### ISSUE THREAD

**Issue by overflowy** [pipelight/pipelight#16]
When attempting to globally add the 'pipelight' package using devbox (wrapper around nix), the installation fails due to incompatibility with the aarch64-darwin platform:

![image](https://github.com/user-attachments/assets/5df0a1be-c177-4870-962d-e94c31749e8a)

You should consider adding aarch64-darwin builds to nix as it will help with the adoption.

**Comment by pipelight** [comment]
I have pushed some changes to .nix files on the dev branch.
Are you able to try them?

**Comment by overflowy** [comment]
[devbox](https://www.jetify.com/devbox/docs/) is a simplified wrapper around nix, I can't interact directly with the .nix files

**Comment by pipelight** [comment]
Does it work with a `devbox global add pipelight#dev` ?

**Comment by overflowy** [comment]
It doesn't work:

![image](https://github.com/user-attachments/assets/7bcfd1ff-eaad-4fff-b30e-e0091e4902c0)

**Comment by pipelight** [comment]
You'll have to wait until I have hands on a keyboard again!
Something like 5 hours!

**Comment by overflowy** [comment]
> You'll have to wait until I have hands on a keyboard again! Something like 5 hours!

No worries, thank you!

**Comment by pipelight** [comment]
Should be good now!!

**Comment by overflowy** [comment]
I finally managed to install it like this:

![image](https://github.com/user-attachments/assets/36ebdd59-2c51-4a72-b9ec-3a0468b83dba)

Thank you!
