### ISSUE TITLE
???: Update the version on deno

### ISSUE THREAD

**Issue by AmeerArsala** [pipelight/pipelight#22]
I believe pipelight's latest version is 0.8.0, but on deno.land, it only shows 0.3.0 as the latest. Is there some type of mistake going on here?

**Comment by pipelight** [comment]
On one hand, Pipelight is the tool that processes the pipeline.
And on another hand, what is on deno are functions that ease pipeline definition.
They are compatible even if minor versions diverge.
So you can use it safely. :smile:

**Comment by AmeerArsala** [comment]
Thanks!
