### ISSUE TITLE
make video to showcase pipelight functionning in a terminal

### ISSUE THREAD

**Issue by pipelight** [pipelight/pipelight#4]
We need to grasp  what pipelight can bring to a project without having to browse through the entire documentation to make an idea.

**Comment by pipelight** [comment]
Gifs on the way

**Comment by bbkane** [comment]
https://github.com/charmbracelet/vhs might be useful here too

**Comment by pipelight** [comment]
Thanks! I have made "tapes" for gif generation in the "examples" root folder!
