### ISSUE TITLE
More information about watcher

### ISSUE THREAD

**Issue by kogeletey** [pipelight/pipelight#8]
Hi again! Coult you tell me more details about watch actions?
I seem to have turned on watcher and added actions `watch`  to pipelines, but nothihg happens

**Comment by pipelight** [comment]
Hi!
You need to explicitly enable the file watcher in your project root directory.

https://pipelight.dev/guide/triggers/definition.html#enable-file-watcher-optional

```sh
pipelight enable watcher
```

This will spawn a pipeligfht instance that watches your directory.

You may want to ignore some files by creating a `.pipelight_ignore` file.

**Comment by kogeletey** [comment]
Yes, I did that. But it just doesn't work.
  This is what is specified in the configuration
 ```toml
[[pipelines.triggers]]
actions = ["watch"]
```

**Comment by kogeletey** [comment]
By the way, options in toml don't work either
Here is my config - https://github.com/kogeletey/karzok/blob/70523714aa847d6d4413cb11b67a1ed0623ac251/pipelight.toml

**Comment by pipelight** [comment]
Okay thanks for the context!
I am troubleshooting this issue and will come back to you ASAP!

**Comment by pipelight** [comment]
Concerning the watcher.
I will need your point of view on the first bug encountered.

I ran the following commands

```sh
pipelight watch --attach
```
```sh
pipelight watch --attach -uu
```

The watcher refuses to start without a `.pipelight_ignore` file in the project root.

Why?:
I initially wanted to let the user decide which file should be watched without any restriction.
Which means, on rare cases, one can watch the .git directory and build directories if needed. 
But watching those path can cause a watch infinite recursion.
Thus the need of an initial .ignore file.

The fixes:

- either create a default `.pipelight_ignore` file with `pipelight init` command.
- or remove the need of an initial `.pipelight_ignore` file by hardcoding unrecommended path depending on the project type (autodetected).

**Comment by kogeletey** [comment]
I caught another interesting bug.
[2024-01-26 17-16-04.webm](https://github.com/pipelight/pipelight/assets/39346864/efdc1f0c-4342-4f61-9ea8-6494bcc69ff2)

Thanks for the clarification, I think it would be better to be able to configure which folder or files to specifically view.
And by default creating a file with ignore would be nice.

**Comment by pipelight** [comment]
pushed to master.
